server:
  port: 8084

spring:
  application:
    name: Payments
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-host:port/eureka/




